### ISSUE TITLE
3.1.7 IncidenceRates

### ISSUE THREAD

**Issue by cebarboza** [darwin-eu-dev/CohortDiagnostics#25]
Add incidence calculation from the IncidencePrevalence package. 

1. executeDiagnostics should provide both options (CD and IncPrev) to perform calculations. 
2. Integrate conditional import (suggest) use of CDMConnector and IncidencePrevalence package. 
3. Integrate results to the Shiny app. 

@ablack3 @cbarbozaerasmus

**Comment by ablack3** [comment]
I'm working on this.

**Comment by rossdwilliams** [comment]
see also #30. We need to have both solutions the rought fast one and the full incprev one available

**Comment by ginberg** [comment]
From the SRS:

> The incidence rate should be calculated, optionally stratified by age (in selected age groups or 10-year bins), gender, and calendar year. The package needs to allow the user for random sampling before this calculation is performed to minimise computing cost. 
> 
> The incidence rate is computed as 1000 * the number of people first entering the cohort / the number of years people were eligible to enter the cohort for the first time. The eligible person time is defined as the time when 
> 
> A person was observed in the database (based on the observation_period table). 
> 
> Had the required amount of prior observation time as specified in the cohort entry event criteria. For example, if the cohort definition requires 365 days of observation prior to cohort entry, patients are not eligible to enter the cohort in the first 365 days of their observation period, and this time is not counted in the eligible time. 
> 
> If the person enters the cohort, then only the time up to cohort entry. Because we only consider the first cohort entry, persons are no longer eligible to enter to cohort after their first entry. 
>
