### ISSUE TITLE
Environment: Set defaults for StudyExecution engine

### ISSUE THREAD

**Issue by cebarboza** [darwin-eu-dev/CohortDiagnostics#26]
Functionality of CD that should be prioritized. 

•  Cohort Definition: Although we don’t use this, if we plan to make the results of cohort diagnostics publicly available for readers of study report and/or publications, I think it is good to keep the cohort definition in the shiny. 
•  Cohort Counts. DESIRABLE: I think it would be great if we could already get an attrition table for the selection of the cohort in each database at this stage. I’ve seen it before as “Inclusion Rule Statistics”, but not sure if we always have it. 
•  Index Event Breakdown 
•  Orphan Concepts: this has been useful to identify concepts that should be included in the cohort definition but were missed. 
•  Cohort Characterization and Temporal characterization: these, as mentioned above, could be run in a cohort sample only. I’m not sure thought that large scale characterization is really needed (some data partners might also have issues to share results without IRB approval). So as Peter said, perhaps we could generate a list of conditions/medications that we would like to include in our table 1 (this could be flexible depending on the study) and run characterization for only those? 
•  Incidence Rates: this is useful to compare results between databases. DESIRABLE: ideally this should be properly calculated. I’m also supportive of a point/period prevalence estimation for benchmarking as Dani suggested.

As possible turn off all other switched in CD.

**Comment by ablack3** [comment]
I think we have this here: https://github.com/darwin-eu-studies/CohortDiagnosticsTemplate
