### ISSUE TITLE
Incidence Rates: executeDiagnostics should provide both options (CD and IncPrev) to perform calculations.

### ISSUE THREAD

**Issue by cebarboza** [darwin-eu-dev/CohortDiagnostics#30]
executeDiagnostics should provide both options (CD and IncPrev) to perform calculations.

**Comment by ablack3** [comment]
Naive question here... why do we want two different incidence rate calculations? Are the PIs looking at both?

**Comment by cebarboza** [comment]
I think the "two calculations" approach was thought when we wanted to push changes to the original OHDSI branch, since we were going to just add the IncidencePrevalence. 

But it would be cool to just have the IncidencePrevalence calculation since that is the one we are using for Darwin studies.

**Comment by ginberg** [comment]
@cebarboza we already have #25 for the incidence rates, shall we close this one?

**Comment by ablack3** [comment]
Let's close this and pivot our effort on CohortDiagnostics away from integrating IncidencePrevalence with the CohortDiagnostics ohdsi package since they are quite different.
