### ISSUE TITLE
CDMConnector - DBI connection support

### ISSUE THREAD

**Issue by ablack3** [darwin-eu-dev/CohortDiagnostics#34]
@rossdwilliams and I were talking about adding CDMConnector or perhaps more specifically DBI support to CohortDiagnostics. 

I think we need to scope out what this change would look like both for interface `executeDiagnostics(dbi_connection)` or `executeDiagnostics(cdmReferenceObject)` and how the internals might change e.g. use `DBI::dbExecute()` instead of `DatabaseConnector::executeSql()`.

Let's talk it out and try to align efforts in Darwin on this. Our goal also would be to make changes that could be accepted back into the OHDSI repo I assume.

**Comment by ginberg** [comment]
@ablack3 I am working on this like we discussed, so I am assigning myself to it. I am pushing my changes to the 'cdm' branch
