### ISSUE TITLE
Failing r check 

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu-dev/CohortDiagnostics#35]
The package seems to be currently failing r check (because it's failing it's own tests). If this is to be relied upon for Darwin studies this should be fixed asap

**Comment by ginberg** [comment]
hi @edward-burn totally agree about that. I made a PR that fixes the R-check, we will merge it soon

**Comment by ginberg** [comment]
this is fixed now. You can see the build status in the [readme ](https://github.com/darwin-eu-dev/CohortDiagnostics)
