### ISSUE TITLE
Time/profile the  different analyses

### ISSUE THREAD

**Issue by ablack3** [darwin-eu-dev/CohortDiagnostics#40]
Can we log some data on how long each step in running CohortDiagnostics?

It would be helpful to see exactly which steps are the longest to run and by how much in a log after running CohortDiagnostics.

Tagging @ginberg, @rossdwilliams

**Comment by rossdwilliams** [comment]
we have this information already @cebarboza can you share this with @ablack3

**Comment by cebarboza** [comment]
I started to share the data we have. It is kind of old now, but will give an idea.
