### ISSUE TITLE
Problem deploying cohort diagnostics app to posit connect

### ISSUE THREAD

**Issue by ablack3** [darwin-eu-dev/CohortDiagnostics#47]
I want to share the cohort diagnostics results with the internal study team. The app starts fine on my laptop. It also will deploy to posit connect. However the app fails to start on the connect server. There is not really any helpful error message. The R logs need to be investigated using the admin dashboard I think.

<img width="1038" alt="image" src="https://github.com/darwin-eu-dev/CohortDiagnostics/assets/10227522/8730a9b0-ea25-41a6-86db-c6646c6bc49c">

**Comment by ablack3** [comment]
[
[export_ipci.zip](https://github.com/darwin-eu-dev/CohortDiagnostics/files/14852477/export_ipci.zip)
](url)

here are the results. 
First run 

```
CohortDiagnostics::createMergedResultsFile("~/Desktop/export_ipci")

CohortDiagnostics::launchDiagnosticsExplorer("MergedCohortDiagnosticsData.sqlite")
```
to view the app locally and then try to deploy it to posit connect https://data-dev.darwin-eu.org/connect

**Comment by ginberg** [comment]
hi @ablack3, I will have a look at it. It has probably something to do with dependencies if you are able to run it locally

**Comment by ablack3** [comment]
oh weird. ok thank you. why would your deployment work but mine not work?
