### ISSUE TITLE
3.1.3 Cohort definition 

### ISSUE THREAD

**Issue by ginberg** [darwin-eu-dev/CohortDiagnostics#64]
> Study cohorts may be defined using a JSON derived from ATLAS/ CAPR but may also have been created using bespoke code in the case of complex studies. CohortDiagnostics should work with cohorts created either using a JSON definition or programmatically in R. The latter is important so that diagnostics can be run for both the Off-The-Shelf studies and complex studies. 
> 
> This should include, per cohort: 
> 
> * the name and description of the cohort 
> 
> * the specification of the cohort in JSON/SQL (where applicable)  
> 
> * the concept sets related to the cohort (where applicable)

**Comment by ginberg** [comment]
@ablack3 you would like to work on this right? Maybe you want to split this up in multiple gh issues?

**Comment by ablack3** [comment]
After discussions I think we are pivoting away from this path since it won't likely be able to be merged into Hades. So all cohort definitions in CohortDiagnostics should be Circe compatible cohort definitions from Atlas or CohortGenerator.
